server:
  port: 9000
spring:
  profiles:
    active: dev
  name: wall-service
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      show_sql: true
      format_sql: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true