spring:
  datasource:
    url: jdbc:mysql://localhost:3308/pyo-service?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123itv456
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
  flyway:
    clean-on-validation-error: true
    baseline-on-migrate: true