version: "3.7"

services:
  pyo-db:
    image: mysql:8.0.21
    container_name: pyo-db
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_DATABASE=pyo-service
      - MYSQL_ROOT_PASSWORD=123itv456
      - MYSQL_USER=pyo-user
      - MYSQL_PASSWORD=123itv456